---
- name: Install needed packages
  become: true
  apt:
    name: "{{ base_packages }}"
    state: latest
    update_cache: yes

- name: Add user cunha
  become: true
  user:
    name: cunha
    groups: sudo,
    append: yes
    password: $6$OntSql4.a$O9qxiDGHjmvM1o6LTt54rSq9jr//.KiS9xJqq7zd6KUHDrQH.hE5mYtwdAKa9Xi6X.CuASuzitSzJQW3Kvv230

- name: Add SSH pubkey
  become: true
  authorized_key:
    user: cunha
    key: "{{ lookup('file', 'files/id_rsa_cunha.pub') }}"
    exclusive: no

- name: Copy .ssh/config
  become: true
  copy:
    src: "{{ lookup('env', 'HOME') }}/.ssh/config"
    dest: /home/cunha/.ssh/config
    owner: cunha
    group: cunha
    mode: 0600

- name: Give user ability to run commands w/o password
  become: true
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%sudo ALL\='
    line: 'cunha ALL=(ALL:ALL) NOPASSWD:ALL'
    validate: '/usr/sbin/visudo -cf %s'

- name: Set sudo secure path
  become: true
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^Defaults secure_path\='
    line: 'Defaults secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"'
    validate: '/usr/sbin/visudo -cf %s'

- name: Remove requiretty from sudoers file
  become: true
  lineinfile:
    dest: /etc/sudoers
    state: absent
    regexp: '^Defaults.*requiretty'

- name: Disable PasswordAuthentication on SSH server
  become: true
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    regexp: '.*PasswordAuthentication.*'
    line: 'PasswordAuthentication no'

- name: Restart SSH server
  become: true
  service:
    name: ssh
    enabled: yes
    state: restarted
