---
- name: Cloning Helix
  git:
    repo: "{{ helix_repo }}"
    dest: "{{ helix_clone_dir }}"
    update: yes
    clone: yes
  register: githelix

- name: Building Helix
  command:
    cmd: /home/cunha/.cargo/bin/cargo install --path helix-term
    chdir: "{{ helix_clone_dir }}"
  when: githelix.changed

- name: Fetching grammars
  command: /home/cunha/.cargo/bin/hx --grammar fetch

- name: Building grammars
  command: /home/cunha/.cargo/bin/hx --grammar build

- name: Removing Helix build files
  file:
    path: "{{helix_clone_dir}}/target"
    state: absent