---
- name: Cloning Helix
  git:
    repo: "{{ helix_repo }}"
    dest: "{{ helix_clone_dir }}"
    update: yes
    clone: yes
  register: githelix

- name: Building Helix
  command:
    cmd: /home/cunha/.cargo/bin/cargo install --path helix-term
    chdir: "{{ helix_clone_dir }}"
  when: githelix.changed

- name: Fetching grammars
  shell:
    cmd: "source /home/cunha/.profile && hx --grammar fetch"
    executable: /bin/bash
  when: githelix.changed

- name: Building grammars
  shell:
    cmd: "source /home/cunha/.profile && hx --grammar build"
    executable: /bin/bash
  when: githelix.changed
