---
- name: Install Docker
  hosts: targets
  gather_facts: true
  vars:
    username: cunha
    docker_group: docker
    docker_packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      - python3-docker
  tasks:
    - name: Add Docker repository key
      become: true
      ansible.builtin.apt_key:
        url: "https://download.docker.com/linux/debian/gpg"
        id: "0EBFCD88"
        state: present

    - name: Add Docker repository and update apt cache
      become: true
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        state: present
        filename: docker
        update_cache: true

    - name: Install Docker
      become: true
      ansible.builtin.apt:
        name: "{{ docker_packages }}"
        state: present
        cache_valid_time: 86400
        update_cache: true

    - name: Update Docker packages
      become: true
      ansible.builtin.apt:
        name: "{{ docker_packages }}"
        state: latest
        cache_valid_time: 86400

    - name: Create a group for Docker users
      become: true
      ansible.builtin.group:
        name: "{{ docker_group }}"
        state: present

    - name: Let user run Docker without sudo
      become: true
      ansible.builtin.user:
        name: "{{ username }}"
        groups: "{{ docker_group }}"
        append: true
        state: present

    - name: Start Docker
      become: true
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true
