---
- name: Push SSH config
  hosts: targets
  gather_facts: true
  tasks:
    - name: Create secrets direectory
      ansible.builtin.file:
        path: "~/.config/secrets"
        state: "directory"
        mode: "0755"
    - name: Push Atuin key
      ansible.builtin.copy:
        src: "{{ lookup('env', 'HOME') }}/.config/secrets/atuin_key"
        dest: "~/.config/secrets/atuin_key"
        force: false
        mode: "0400"

