---
- name: Generate password
  ansible.builtin.set_fact:
    user_password: "{{ lookup('password', '/dev/null length=16 chars=ascii_letters,digits') }}"
  with_items: "{{ user_list }}"
  register: passwords

- name: Create users
  become: true
  ansible.builtin.user:
    name: "{{ item.item }}"
    password: "{{ item.ansible_facts.user_password | password_hash('sha512') }}"
    state: present
  with_items: "{{ passwords.results }}"

- name: Save password to file
  become: true
  ansible.builtin.copy:
    content: "{{ item.ansible_facts.user_password }}"
    dest: "/home/{{ item.item }}/password.txt"
    owner: "{{ item.item }}"
    mode: 400
  with_items: "{{ passwords.results }}"

- name: Add SSH pubkey
  become: true
  ansible.builtin.authorized_key:
    user: "{{ item }}"
    key: "{{ lookup('file', item) }}"
    exclusive: false
  with_items: "{{ user_list }}"

- name: Give sudo permissions
  become: true
  ansible.builtin.user:
    name: "{{ item }}"
    groups: sudo
    append: true
  with_items: "{{ user_list }}"
  when: give_sudo
