---
- name: Install UI packages
  become: true
  become_user: root
  apt:
    name: "{{ cunha_ui_packages }}"
    state: latest
    cache_valid_time: 600

- name: Install optional UI packages
  become: true
  become_user: root
  apt:
    name: "{{ cunha_ui_packages_nofail }}"
    state: latest
    cache_valid_time: 600

- name: Set shell to zsh
  become: true
  become_user: root
  user:
    name: cunha
    shell: /usr/bin/zsh

- name: Create cache directory
  file:
    path: /home/cunha/.cache
    state: directory
    mode: 0755

# - name: Initialize vcsh/mr repository
#   shell: vcsh init mr
#   args:
#     creates: /home/cunha/.config/vcsh/repo.d/mr.git/config

# - name: Add remote for vcsh/mr
#   shell: grep origin /home/cunha/.config/vcsh/repo.d/mr.git/config || vcsh mr remote add origin git@github.com:cunha/dotmr.git

# - name: Pull vcsh/mr
#   shell: vcsh mr pull origin master

# - name: Set upstream for vcsh/mr
#   shell: vcsh mr branch --set-upstream-to=origin/master master

# - name: Fetching all repositories
#   shell: mr update

# - name: Updating FZF
#   command: /home/cunha/bin/update-fzf
