---
- name: Install UI packages
  become: true
  become_user: root
  apt:
    name: "{{ cunha_ui_packages }}"
    state: latest
    cache_valid_time: 600

- name: Install optional UI packages
  become: true
  become_user: root
  apt:
    name: "{{ cunha_ui_packages_nofail }}"
    state: latest
    cache_valid_time: 600

- name: Create cache directory
  file:
    path: /home/cunha/.cache
    state: directory
    mode: 0755

- name: Initialize .dotfiles
  shell: git init --bare /home/cunha/.dotfiles
  args:
    creates: /home/cunha/.dotfiles

- name: Disable showUntrackedFiles
  shell: git --git-dir=/home/cunha/.dotfiles --work-tree=/home/cunha config status.showUntrackedFiles no

- name: Add git@github.com:cunha/dotfiles.git as remote
  shell: git --git-dir=/home/cunha/.dotfiles --work-tree=/home/cunha remote add origin git@github.com:cunha/dotfiles.git
  ignore_errors: yes

- name: Fetch dotfiles repo contents
  shell: git --git-dir=/home/cunha/.dotfiles --work-tree=/home/cunha fetch

- name: Removing commonly created files/directories before checkout
  file:
    path: "/home/cunha/{{item}}"
    state: absent
  with_items: "{{ paths_to_remove_before_checkout }}"

- name: Checking out dotfiles
  shell: git --git-dir=/home/cunha/.dotfiles --work-tree=/home/cunha checkout master

# - name: Set shell to zsh
#   become: true
#   become_user: root
#   user:
#     name: cunha
#     shell: /usr/bin/zsh

- name: Cloning dein into .vim/plugins
  git:
    repo: git@github.com:Shougo/dein.vim.git
    dest: /home/cunha/.vim/plugins/dein.vim
    update: yes
    clone: yes

# - name: Updating FZF
#   command: /home/cunha/bin/update-fzf
