---
# - name: Add stretch-backports to APT sources
#   become: true
#   apt_repository:
#     repo: "deb http://deb.debian.org/debian/ {{ansible_distribution_release}}-backports main non-free-contrib"
#     filename: backports
#     state: present
#     update_cache: yes

# - name: Set repo preferences
#   become: true
#   copy:
#     src: dist.prefs
#     dest: /etc/apt/preferences.d/dist.prefs
#     backup: yes

- name: Install needed packages
  become: true
  become_user: root
  apt:
    name: "{{ cunha_ui_packages }}"
    state: latest
    update_cache: yes

# - name: Install backported packages
#   become: true
#   become_user: root
#   apt:
#     name: "{{ cunha_backported_packages }}"
#     state: latest
#     default_release: "{{ansible_distribution_release}}-backports"
#     cache_valid_time: 600

- name: Set shell to zsh
  become: true
  become_user: root
  user:
    name: cunha
    shell: /usr/bin/zsh

- name: Create cache directory
  file:
    path: /home/cunha/.cache
    state: directory
    mode: 0755

- name: Initialize vcsh/mr repository
  shell: vcsh init mr
  args:
    creates: /home/cunha/.config/vcsh/repo.d/mr.git/config

- name: Add remote for vcsh/mr
  shell: grep origin /home/cunha/.config/vcsh/repo.d/mr.git/config || vcsh mr remote add origin git@github.com:cunha/dotmr.git

- name: Pull vcsh/mr
  shell: vcsh mr pull origin master

- name: Set upstream for vcsh/mr
  shell: vcsh mr branch --set-upstream-to=origin/master master

- name: Fetching all repositories
  shell: mr update

- name: Updating FZF
  command: /home/cunha/bin/update-fzf
