[editor]
bufferline = "always"
color-modes = true
cursorline = true
line-number = "relative"
true-color = true
auto-pairs = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
skip-levels = 1

[editor.statusline]
left = ["mode", "spinner", "spacer", "file-name", "file-type"]
center = []
right = ["diagnostics", "selections", "position", "total-line-numbers", "file-encoding"]

[editor.whitespace]
render = "all"

[editor.whitespace.characters]
space = " "
nbsp = "⍽"
tab = "→"
newline = "¬"
tabpad = " "

[keys.insert]
"A-left" = "move_prev_word_end"
"A-right" = "move_next_word_start"
"C-backspace" = "delete_word_backward"
"C-del" = "delete_word_forward"

[keys.normal]
"A-j" = "goto_previous_buffer"
"A-k" = "goto_next_buffer"
"A-h" = "jump_view_left"
"A-l" = "jump_view_right"
"C-q" = ":reflow"

