[editor]
auto-pairs = false
bufferline = "always"
color-modes = true
cursorline = true
line-number = "relative"
rulers = [80]
true-color = true

[editor.soft-wrap]
enable = true
wrap-at-text-width = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.file-picker]
hidden = true
git-ignore = true

[editor.indent-guides]
render = true
skip-levels = 1

[editor.statusline]
left = ["mode", "spinner", "spacer", "file-name", "file-type"]
center = []
right = ["diagnostics", "selections", "position", "total-line-numbers", "file-encoding"]

[editor.whitespace]
render = "all"

[editor.whitespace.characters]
space = " "
nbsp = "⍽"
tab = "→"
newline = "¬"
tabpad = " "

[keys.insert]
"A-left" = "move_prev_word_end"
"A-right" = "move_next_word_start"
"C-backspace" = "delete_word_backward"
"C-del" = "delete_word_forward"
"C-w" = "normal_mode"
"C-A-S-a" = "normal_mode"

[keys.normal]
"A-k" = "goto_previous_buffer"
"A-j" = "goto_next_buffer"
"A-h" = "jump_view_left"
"A-l" = "jump_view_right"
"C-w" = ":reflow"
"pageup" = "half_page_up"
"pagedown" = "half_page_down"
# "C-d" = "jump_forward"
# "C-f" = "jump_backward"
"C-e" = "repeat_last_motion"
"}" = "goto_next_paragraph"
"{" = "goto_prev_paragraph"
"A-z" = ":toggle soft-wrap.enable"

[keys.select]
"pageup" = "half_page_up"
"pagedown" = "half_page_down"
# "C-d" = "jump_forward"
# "C-f" = "jump_backward"
"C-e" = "repeat_last_motion"



