[language-server.ltex]
name = "ltex"
command = "ltex-ls"
# args = ["--log-file=/Users/cunha/ltex.log"]

[language-server.ruff]
name = "ruff"
command = "ruff"
args = ["server"]

[language-server.pylsp]
name = "pylsp"
command = "pylsp"
args = ["--log-file=/Users/cunha/.cache/pylsp.log", "-vvvv"]
# pylsp.plugins.pylint.enabled = true
# pylsp.plugins.rope.enabled = true
# pylsp.plugins.flake8.enabled = true
# pylsp.plugins.autopep8.enabled = false
# pylsp.plugins.mccabe.enabled = false
# pylsp.plugins.pycodestyle.enabled = false
# pylsp.plugins.pyflakes.enabled = false
# pylsp.plugins.flake8.maxLineLength = 88

[language-server.pylsp.config.pylsp.plugins]
# flake8 includes pycodestyle, mccabe, pyflakes
flake8 = {enabled = false, ignore = ["E501"]}
autopep8 = {enabled = false}
mccabe = {enabled = false}
pycodestyle = {enabled = false}
pyflakes = {enabled = false}
pylint = {enabled = false}
yapf = {enabled = false}
rope = {enabled = true}
rope_autoimport.enabled = true
rope_rename.enabled = true

# [language-server.pyright]
# name = "pyright"
# command = "pyright"

# [language-server.pyright.config.python.analysis]
# typeCheckingMode = "strict"

# [language-server.pylyzer]
# name = "pylyzer"
# command = "pylyzer"
# config = { settings = { args = ["--server"] } }

[language-server.texlab]
name = "texlab"
command = "texlab"
# args = ["-vvvv", "--log-file", "texlab.log"]

[language-server.texlab.config]
# tectonic isn't working on IEEEtran.cls:
# texlab.build.executable = "tectonic"
# texlab.build.args = [
#   "-X",
#   "compile",
#   "%f",
#   "--synctex",
#   "--keep-logs",
#   "--keep-intermediates",
#   "-Zshell-escape"
# ]
texlab.build.executable = "latexmk"
texlab.build.args = [
  "-pdf",
  "-interaction=nonstopmode",
  "-synctex=1",
  "%f"
]
# calls Skim and causes the terminal to lose focus:
# texlab.build.forwardSearchAfter = true  
texlab.build.onSave = true
texlab.chktex.onOpenAndSave = true
texlab.formatterLineLength = 78
texlab.forwardSearch.executable = "/Applications/Skim.app/Contents/SharedSupport/displayline"
texlab.forwardSearch.args = ["%l", "%p", "%f"]


# Loading dictionary files does not work yet:
# https://github.com/helix-editor/helix/discussions/5450
# [language-server.ltex.config.ltex]
# dictionary = { "en-US" = [ ":~/.config/ltex/dictionary.en-US.txt" ], "pt-BR" = [ ":/Users/cunha/.config/ltex/dictionary.pt-BR.txt" ] }

[[language]]
name = "bash"
auto-format = false
indent = { tab-width = 4, unit = "spaces" }
rulers = [80]

[[language]]
name = "python"
rulers = [100]
# language-servers = [ { name = "pylsp" } ]
language-servers = [ { name = "pylsp" }, { name = "ruff" } ]
formatter = { command = "ruff", args = [ "format", "-" ] }

# [language.formatter]
# command = "black"
# args = ["-", "--quiet"]

[[language]]
name = "rust"
rulers = [100]

[[language]]
name = "latex"
indent = { tab-width = 4, unit = " " }
diagnostic-severity = "Hint"
rulers = [80]
text-width = 78
language-servers = [{ name = "texlab" }, { name = "ltex" }]

[[language]]
name = "markdown"
text-width = 78
language-servers = [{ name = "marksman" }, { name = "ltex" }]

[[language]]
name = "text"
language-servers = [{ name = "ltex" }]
scope = "text.plain"
roots = []
file-types = ["txt", "text"]
