[language-server.ltex]
name = "ltex"
command = "/opt/homebrew/bin/ltex-ls"
# args = ["--log-file=/Users/cunha/ltex.log"]

# Loading dictionary files does not work yet:
# https://github.com/helix-editor/helix/discussions/5450
# [language-server.ltex.config.ltex]
# dictionary = { "en-US" = [ ":~/.config/ltex/dictionary.en-US.txt" ], "pt-BR" = [ ":/Users/cunha/.config/ltex/dictionary.pt-BR.txt" ] }

[[language]]
name = "bash"
auto-format = false
indent = { tab-width = 4, unit = "spaces" }
rulers = [80]

[[language]]
name = "python"
rulers = [100]

# [language.config]
# pylsp.plugins.autopep8.enabled = false
# pylsp.plugins.mccabe.enabled = false
# pylsp.plugins.pycodestyle.enabled = false
# pylsp.plugins.pyflakes.enabled = false
# pylsp.plugins.pylint.enabled = true
# pylsp.plugins.flake8.enabled = true
# pylsp.plugins.flake8.maxLineLength = 88

# [language.formatter]
# command = "black"
# args = ["-", "--quiet"]

[[language]]
name = "rust"
rulers = [100]

[[language]]
name = "latex"
indent = { tab-width = 4, unit = " " }
diagnostic-severity = "Hint"
rulers = [80]
text-width = 78
language-servers = [{ name = "texlab" }, { name = "ltex" }]

# [language.config]
# texlab.build.executable = "tectonic"
# texlab.build.args = [
#   "-X",
#   "compile",
#   "%f",
#   "--synctex",
#   "--keep-logs",
#   "--keep-intermediates",
# ]
# texlab.build.forwardSearchAfter = true
# texlab.build.onSave = true
# texlab.chktex.onOpenAndSave = true
# texlab.formatterLineLength = 78
# texlab.forwardSearch.args = ["%l", "%p", "%f"]
# texlab.forwardSearch.executable = "/Applications/Skim.app/Contents/SharedSupport/displayline"

[[language]]
name = "markdown"
text-width = 78
language-servers = [{ name = "marksman" }, { name = "ltex" }]

[[language]]
name = "text"
language-servers = [{ name = "ltex" }]
scope = "text.plain"
roots = []
file-types = ["txt", "text"]
